### ISSUE TITLE
Page refresh sustains open views

### ISSUE THREAD

**Issue by acomrie** [magland/sortingview#100]
Not sure if this will be possible, but it would be awesome if upon refreshing the sortingview page in a browser, the currently open views were maintained. Currently, upon refresh, all the views close and the user must reopen the units table and any other views, in addition to reselecting previously selected units, etc.

Thank you.

**Comment by magland** [comment]
@acomrie This is possible by storing the state in localStorage (browser storage). However, it might be a little deceptive because the shared URL would not include this state (I think the possible state is too large to store in the URL). We could make this a bit more clear by not restoring the state by default, but having a "restore open windows?" button appear on page load. What do you think?

**Comment by acomrie** [comment]
Hi @magland, thank you. That's helpful context, I certainly wasn't considering how this would interact with shared URLs. I think the restore open windows button could be helpful (if it is practical on your end/easy enough to coordinate across concurrent users of a given sort workspace). A perhaps preferable alternative is also just to make sure all the latencies are really as fast and optimized as possible, in which case I/users wouldn't be so inclined to refresh the browser page in the first place. Thoughts? See some extra comments on closed #10

**Comment by magland** [comment]
I requested creating two new issue for the slowness. See my comment on #10

**Comment by magland** [comment]
I'll work on functionality for restoring some state (stored in localStorage).

**Comment by magland** [comment]
Not going to do this now. This capability will need to be added to figurl at some point.
