### ISSUE TITLE
Don't subsample when small spike count?

### ISSUE THREAD

**Issue by acomrie** [magland/sortingview#125]
Autocorrelograms and several other views are subsampled, which is usually great. However, for units with small numbers of spikes (say <1000 spikes in total across the entire recording, just to throw something out there), the plots look sparse enough that they are difficult to evaluate, because the apparent sparsity may be real or may be due to the subsampling. Might it be reasonable or possible to use all spikes rather than subsampling for views of the units that have small total spike counts? As always, certainly open to other thoughts here. Thanks much!

**Comment by magland** [comment]
Right now the correlogram code looks like this:

```python
@kc.taskfunction('fetch_correlogram_plot_data.6', type='pure-calculation')
def task_fetch_correlogram_plot_data(*, sorting_object, unit_x, unit_y=None, subsample: bool):
    with hi.Config(
        job_cache=job_cache,
        job_handler=job_handler.correlograms
    ):
        with hi.Config(
            job_handler=job_handler.misc
        ):
            if subsample:
                sorting_object_subsampled = subsample_sorting.run(
                    sorting_object=sorting_object,
                    segment_size_sec=10,
                    num_segments=100
                )
            else:
                sorting_object_subsampled = sorting_object
        return fetch_correlogram_plot_data.run(
            sorting_object=sorting_object_subsampled,
            unit_x=unit_x,
            unit_y=unit_y
        )
```

Note that the subsampling is hard-coded to sample 100 segments of size 10 seconds each. This works well, I think, if average firing rate is >= 1 Hz (then you get around 1000 events). However, you are correct in pointing out that if the firing rate is less than this, we may not sample enough events.

So my first thought is that we'll want to do is change the `subsample_sorting` function to take in different arguments:

Something like:
```python
               sorting_object_subsampled = subsample_sorting.run(
                    sorting_object=sorting_object,
                    target_num_events=1000,
                    segment_size_sec=10
                )
```

And then inside the function, it would automatically determine the num_segments based on the average firing rates of the two units. However, this is a problem because then different units would be sampled differently. The issue is that the same cached `subsample_sorting` function output is used for computing all correlograms. So I'm not sure about how to best resolve this.

One possibility is to simply use more segments by default - like 50. That should cover the case where firing rate is >= 0.2 Hz.

Thoughts? @acomrie @jsoules

**Comment by magland** [comment]
Oops, Jeff pointed out that I made a mistake with my back-of-the-envelope calculations. Right now, 1Hz would give us only 100 events (not 1000), and so increasing to 50 segments may still not be enough. Maybe we should increase to 100 segments - that way we are sampling 1000 seconds, and that would give 200 events for even 0.2Hz firing rate...

**Comment by acomrie** [comment]
Thanks. The general increase in number of segments/total time sampled makes sense! And I agree it seems more sound than differently subsampling different units. With that logic, my initial thought to basically toggle the subsample bool argument by thresholding total num spikes on a unit doesn't sound so good either.

What I don't have a great sense of is the tradeoff here in terms of compute time - would you expect an increased number of segments to increase the autocorr time-to-load much, or would the slowdown happen only once (say, the first time they're computed), and after that the retrieval is about the same regardless of the amount of data in each plot?

**Comment by magland** [comment]
I'll increase the sampling and we can see how that affects the compute time.

**Comment by magland** [comment]
I looked at my messages above and I realize that the existing number of segments is  already 100 (sorry for that confusion). I will increase that to 500 and we'll see if that slows things down too much. When I make this change, all correlograms will need to be recomputed.

**Comment by magland** [comment]
Working on this here: https://github.com/magland/sortingview/pull/139
