### ISSUE TITLE
Persistent state

### ISSUE THREAD

**Issue by khl02007** [magland/sortingview#29]
Right now when I refresh the page all the widgets close. This then makes the user do a bit of work opening up the widgets and finding where they had left off. Is it possible to make the state of the widgets persist across different sessions?

**Comment by magland** [comment]
Right now all the persistent state is stored in the URL. We could also store more complex state there, but it could make the URL query string quite long. I'd prefer not to do that.

It's also possible to store the state in the browser localStorage. But that state would not be transferred when sharing a link (or when opening that link at a later date).

Maybe the simplest way to do this is to use [react-beforeunload](https://www.npmjs.com/package/react-beforeunload) or similar to intercept the refresh, and then store some state in localStorage. However, on page reload, we need to determine under which conditions that state should be retrieved from localStorage. For example, if we changed the URL to point to a different sorting, then we would not want to load the state.

@jsoules, do you have any thoughts? Trying to keep this simple.

**Comment by jsoules** [comment]
Wanted to do a little thinking and background reading before replying on this.

I appreciate the desire to keep the query strings straightforward, but it would be nice to allow users to share specific widget state. On the other hand, the localStorage solution is (as you say) a pretty elegant solution, and would have the added advantage of persisting a workspace state between window closes (assuming the user doesn't manually close all the widget windows first). So that's added utility there.

And it looks like beforeUnload fires even when the tab/window/browser is closing--so that's nice too.

I think I would lean that way, but we'll just have to be careful so we don't wind up with silly behavior (like resetting to the preserved state every time the user tries to open/close a widget).
