### ISSUE TITLE
curation labels of merged units

### ISSUE THREAD

**Issue by khl02007** [magland/sortingview#62]
Right now if it is possible for the user to give different curation labels (e.g. 'accept' and 'reject') to two units that are merged. I think it would be better if two units that were merged always got the same label (e.g. if you set label to one, automatically set the same label to the other). If one tries to merge two units that already have different curation labels, merge them and then reset the labels.

**Comment by magland** [comment]
Sounds good, but there are different ways to handle this - let's try to get it right. What about the following scenario:

Label unit 2 as rejected
Merge units 1 and 2 (now 1 becomes rejected)
Unmerge units 1 and 2 (now 1 has been rejected, but maybe that's not what we want)

You can imagine other similar things that could happen

**Comment by khl02007** [comment]
I see, good point. How about always resetting the curation label of the units upon a merge (or un-merge)? So in the situation you describe, after merging, the labels for both units 1 and 2 (which are now part of the merged unit) gets cleared (i.e. set to nothing) regardless of what they were before. This forces the user to re-assign the label to the merged unit, which is probably not a bad thing. And when the merge is un-done, the labels for the two units again get cleared and the user has to re-assign them.

**Comment by magland** [comment]
That sounds better. I propose that we use intersection for merges. So, in order for a label to survive a merge it must be present on all of the units being merged. So if only one unit has the rejected label, that label will be removed. Upon unmerging, all the labels stick.

**Comment by khl02007** [comment]
That sounds good to me

**Comment by magland** [comment]
Having some second thoughts about this now that I'm looking into the implementation. I think the more natural thing to do is:

* Labels apply to individual units rather than merge groups. So, it is is possible to have different labels for different units within a merge group. The advantage is that merging followed by unmerge does not affect labels, and we don't need to worry about complex intersection/union rules for labels during merge.
* In the GUI, of you apply a label to a merged unit, then that label gets set on all the units within the merge group.
* In the GUI, labels for a merge group can show up as grayed out if they only apply to some but not all of the units in the group. And we can also display a warning that this should be resolved. We could also add a button that would do some kind of label cleanup.
* For purposes of viewing options in the GUI (hide rejected, etc), labels only apply if they are set for all units in the group.

Generally, from an implementation perspective, it will be a lot easier if we can retain the per-unit labels and not automatically adjust them during merge/unmerge operations.
